-- AGRICULTURAL FARM MANAGEMENT SYSTEM
-- Group 12
-- Phases 4-7: Physical Design, Data Population, Database Programming, Security
-- Target DBMS: PostgreSQL
-- Scope kept simple and aligned with the approved project requirements.

DROP VIEW IF EXISTS sales_summary_view, harvest_summary_view, fertilizer_stock_view,
    worker_crop_view, crop_production_view CASCADE;

DROP TABLE IF EXISTS sale_item, harvest_worker, fertilizer_usage,
    equipment_maintenance, equipment_assignment, crop_worker,
    sale, customer, harvest, fertilizer, equipment, worker, crop, farm CASCADE;

-- PHASE 4: PHYSICAL DESIGN / DDL


CREATE TABLE farm (
    farm_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_name        VARCHAR(100) NOT NULL UNIQUE,
    location         VARCHAR(150) NOT NULL,
    total_size       NUMERIC(10,2) NOT NULL CHECK (total_size > 0)
);

CREATE TABLE crop (
    crop_id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id                 INTEGER NOT NULL,
    crop_type               VARCHAR(80) NOT NULL,
    planting_date           DATE NOT NULL,
    expected_harvest_date   DATE NOT NULL,
    status                  VARCHAR(20) NOT NULL DEFAULT 'Planned'
                            CHECK (status IN ('Planned','Growing','Harvested','Completed')),
    plot_number             VARCHAR(30) NOT NULL,
    CONSTRAINT fk_crop_farm FOREIGN KEY (farm_id) REFERENCES farm(farm_id),
    CONSTRAINT chk_crop_dates CHECK (expected_harvest_date >= planting_date),
    CONSTRAINT uq_farm_plot_crop UNIQUE (farm_id, plot_number)
);

CREATE TABLE worker (
    worker_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     VARCHAR(20) NOT NULL UNIQUE,
    fname           VARCHAR(50) NOT NULL,
    lname           VARCHAR(50) NOT NULL,
    contact_details VARCHAR(100) NOT NULL,
    job_role        VARCHAR(60) NOT NULL,
    hire_date       DATE NOT NULL
);

CREATE TABLE equipment (
    equipment_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_name  VARCHAR(100) NOT NULL,
    equipment_type  VARCHAR(60) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'Available'
                    CHECK (status IN ('Available','In Use','Under Maintenance'))
);

CREATE TABLE fertilizer (
    fertilizer_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fertilizer_type VARCHAR(80) NOT NULL UNIQUE,
    stock_level     NUMERIC(10,2) NOT NULL CHECK (stock_level >= 0),
    unit            VARCHAR(20) NOT NULL
);

CREATE TABLE harvest (
    harvest_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id         INTEGER NOT NULL,
    harvest_date    DATE NOT NULL,
    quantity        NUMERIC(10,2) NOT NULL CHECK (quantity > 0),
    CONSTRAINT fk_harvest_crop FOREIGN KEY (crop_id) REFERENCES crop(crop_id)
);

CREATE TABLE customer (
    customer_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(100) NOT NULL,
    contact_details VARCHAR(100) NOT NULL,
    address         VARCHAR(150) NOT NULL
);

CREATE TABLE sale (
    sale_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     INTEGER NOT NULL,
    sale_date       DATE NOT NULL,
    invoice_number  VARCHAR(30) NOT NULL UNIQUE,
    total_amount    NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    CONSTRAINT fk_sale_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
);

-- Worker <-> Crop
CREATE TABLE crop_worker (
    crop_worker_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id         INTEGER NOT NULL,
    worker_id       INTEGER NOT NULL,
    assigned_date   DATE NOT NULL,
    task_role       VARCHAR(80) NOT NULL,
    CONSTRAINT fk_crop_worker_crop FOREIGN KEY (crop_id) REFERENCES crop(crop_id),
    CONSTRAINT fk_crop_worker_worker FOREIGN KEY (worker_id) REFERENCES worker(worker_id),
    CONSTRAINT uq_crop_worker UNIQUE (crop_id, worker_id, assigned_date)
);

-- Worker <-> Equipment
CREATE TABLE equipment_assignment (
    assignment_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id    INTEGER NOT NULL,
    worker_id       INTEGER NOT NULL,
    assigned_date   DATE NOT NULL,
    return_date     DATE,
    CONSTRAINT fk_equipment_assignment_equipment
        FOREIGN KEY (equipment_id) REFERENCES equipment(equipment_id),
    CONSTRAINT fk_equipment_assignment_worker
        FOREIGN KEY (worker_id) REFERENCES worker(worker_id),
    CONSTRAINT chk_equipment_dates
        CHECK (return_date IS NULL OR return_date >= assigned_date)
);

CREATE TABLE equipment_maintenance (
    maintenance_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id    INTEGER NOT NULL,
    maintenance_date DATE NOT NULL,
    description     VARCHAR(200) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'Completed'
                    CHECK (status IN ('Scheduled','Completed')),
    CONSTRAINT fk_maintenance_equipment
        FOREIGN KEY (equipment_id) REFERENCES equipment(equipment_id)
);

-- Fertilizer usage
CREATE TABLE fertilizer_usage (
    usage_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fertilizer_id   INTEGER NOT NULL,
    crop_id         INTEGER NOT NULL,
    quantity_used   NUMERIC(10,2) NOT NULL CHECK (quantity_used > 0),
    usage_date      DATE NOT NULL,
    CONSTRAINT fk_usage_fertilizer FOREIGN KEY (fertilizer_id) REFERENCES fertilizer(fertilizer_id),
    CONSTRAINT fk_usage_crop FOREIGN KEY (crop_id) REFERENCES crop(crop_id)
);

-- Worker <-> Harvest activity
CREATE TABLE harvest_worker (
    harvest_worker_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    harvest_id        INTEGER NOT NULL,
    worker_id         INTEGER NOT NULL,
    assigned_date     DATE NOT NULL,
    task_role         VARCHAR(80) NOT NULL,
    CONSTRAINT fk_harvest_worker_harvest FOREIGN KEY (harvest_id) REFERENCES harvest(harvest_id),
    CONSTRAINT fk_harvest_worker_worker FOREIGN KEY (worker_id) REFERENCES worker(worker_id),
    CONSTRAINT uq_harvest_worker UNIQUE (harvest_id, worker_id)
);

-- Sale <-> Harvest
CREATE TABLE sale_item (
    sale_item_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id         INTEGER NOT NULL,
    harvest_id      INTEGER NOT NULL,
    quantity_sold   NUMERIC(10,2) NOT NULL CHECK (quantity_sold > 0),
    unit_price      NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    CONSTRAINT fk_sale_item_sale FOREIGN KEY (sale_id) REFERENCES sale(sale_id),
    CONSTRAINT fk_sale_item_harvest FOREIGN KEY (harvest_id) REFERENCES harvest(harvest_id)
);

-- Useful indexes only
CREATE INDEX idx_crop_farm ON crop(farm_id);
CREATE INDEX idx_crop_status ON crop(status);
CREATE INDEX idx_harvest_crop ON harvest(crop_id);
CREATE INDEX idx_harvest_date ON harvest(harvest_date);
CREATE INDEX idx_sale_customer ON sale(customer_id);
CREATE INDEX idx_sale_date ON sale(sale_date);
CREATE INDEX idx_fertilizer_usage_crop ON fertilizer_usage(crop_id);
CREATE INDEX idx_equipment_status ON equipment(status);
CREATE INDEX idx_crop_worker_worker ON crop_worker(worker_id);
CREATE INDEX idx_sale_item_harvest ON sale_item(harvest_id);


-- PHASE 5: DATA POPULATION / DML


-- One commercial farm, following the project assumption.
INSERT INTO farm (farm_name, location, total_size) VALUES
('Musanze Green Valley Farm', 'Musanze, Rwanda', 120.50);

INSERT INTO crop (farm_id, crop_type, planting_date, expected_harvest_date, status, plot_number) VALUES
(1,'Irish Potato','2025-01-10','2025-04-15','Harvested','P01'),
(1,'Beans','2025-01-15','2025-04-20','Harvested','P02'),
(1,'Maize','2025-02-01','2025-06-10','Harvested','P03'),
(1,'Carrots','2025-02-10','2025-05-20','Harvested','P04'),
(1,'Tomatoes','2025-02-15','2025-05-30','Harvested','P05'),
(1,'Onions','2025-02-20','2025-06-05','Harvested','P06'),
(1,'Cabbage','2025-03-01','2025-06-15','Harvested','P07'),
(1,'Sweet Potato','2025-03-05','2025-07-10','Harvested','P08'),
(1,'Peas','2025-03-10','2025-06-25','Harvested','P09'),
(1,'Wheat','2025-03-15','2025-07-20','Harvested','P10'),
(1,'Sorghum','2025-03-20','2025-07-25','Harvested','P11'),
(1,'Soybean','2025-04-01','2025-08-01','Harvested','P12'),
(1,'Cucumber','2025-04-05','2025-06-30','Harvested','P13'),
(1,'Pumpkin','2025-04-10','2025-08-15','Harvested','P14'),
(1,'Lettuce','2025-04-15','2025-06-20','Harvested','P15'),
(1,'Garlic','2025-04-20','2025-08-10','Harvested','P16'),
(1,'Cassava','2025-05-01','2025-11-01','Growing','P17'),
(1,'Banana','2025-05-05','2025-10-15','Growing','P18'),
(1,'Green Pepper','2025-05-10','2025-08-20','Growing','P19'),
(1,'Eggplant','2025-05-15','2025-08-25','Growing','P20'),
(1,'Spinach','2025-05-20','2025-07-15','Harvested','P21'),
(1,'Beetroot','2025-05-25','2025-08-05','Harvested','P22'),
(1,'Broccoli','2025-06-01','2025-09-01','Growing','P23'),
(1,'Strawberry','2025-06-05','2025-09-10','Growing','P24'),
(1,'Groundnut','2025-06-10','2025-09-20','Growing','P25');

INSERT INTO worker (employee_id, fname, lname, contact_details, job_role, hire_date) VALUES
('EMP001','Jean','Mugabo','0788000001','Farm Worker','2024-01-10'),
('EMP002','Eric','Niyonzima','0788000002','Farm Worker','2024-01-15'),
('EMP003','Patrick','Habimana','0788000003','Farm Worker','2024-02-01'),
('EMP004','Claude','Nsengimana','0788000004','Farm Worker','2024-02-12'),
('EMP005','Emmanuel','Uwimana','0788000005','Farm Worker','2024-02-20'),
('EMP006','Samuel','Bizimana','0788000006','Farm Worker','2024-03-01'),
('EMP007','Daniel','Ishimwe','0788000007','Farm Worker','2024-03-10'),
('EMP008','Fabrice','Munyaneza','0788000008','Farm Worker','2024-03-20'),
('EMP009','David','Mutesi','0788000009','Farm Worker','2024-04-01'),
('EMP010','Alex','Hakizimana','0788000010','Farm Worker','2024-04-15'),
('EMP011','Kevin','Nshimiyimana','0788000011','Farm Worker','2024-05-01'),
('EMP012','Oscar','Tuyisenge','0788000012','Farm Worker','2024-05-10'),
('EMP013','Felix','Rukundo','0788000013','Farm Worker','2024-05-20'),
('EMP014','Paul','Munyaneza','0788000014','Farm Worker','2024-06-01'),
('EMP015','Theogene','Nsabimana','0788000015','Farm Worker','2024-06-10'),
('EMP016','Andre','Kagabo','0788000016','Farm Worker','2024-07-01'),
('EMP017','Joseph','Twizeyimana','0788000017','Farm Worker','2024-07-15'),
('EMP018','Patrick','Mbarushimana','0788000018','Farm Worker','2024-08-01'),
('EMP019','Emile','Rukundo','0788000019','Farm Worker','2024-08-15'),
('EMP020','Benjamin','Ndayisenga','0788000020','Farm Worker','2024-09-01'),
('EMP021','Alice','Mukamana','0788000021','Farm Worker','2024-09-15'),
('EMP022','Diane','Uwamahoro','0788000022','Farm Worker','2024-10-01'),
('EMP023','Beatrice','Nyirabazungu','0788000023','Farm Worker','2024-10-15'),
('EMP024','Grace','Uwase','0788000024','Farm Worker','2024-11-01'),
('EMP025','Clara','Mukashema','0788000025','Farm Worker','2024-11-15');

INSERT INTO equipment (equipment_name, equipment_type, status) VALUES
('John Deere Tractor 1','Tractor','Available'),
('John Deere Tractor 2','Tractor','Available'),
('Kubota Tractor','Tractor','In Use'),
('Massey Ferguson 1','Tractor','Available'),
('Massey Ferguson 2','Tractor','Under Maintenance'),
('Honda Water Pump 1','Water Pump','Available'),
('Honda Water Pump 2','Water Pump','In Use'),
('Irrigation Pump 1','Water Pump','Available'),
('Irrigation Pump 2','Water Pump','Available'),
('Rotary Tiller 1','Tiller','Available'),
('Rotary Tiller 2','Tiller','In Use'),
('Disc Harrow 1','Harrow','Available'),
('Disc Harrow 2','Harrow','Available'),
('Seed Drill 1','Seeder','Available'),
('Seed Drill 2','Seeder','In Use'),
('Crop Sprayer 1','Sprayer','Available'),
('Crop Sprayer 2','Sprayer','Available'),
('Motor Cultivator 1','Cultivator','Available'),
('Motor Cultivator 2','Cultivator','Under Maintenance'),
('Harvest Cart 1','Transport','Available'),
('Harvest Cart 2','Transport','In Use'),
('Power Weeder 1','Weeder','Available'),
('Power Weeder 2','Weeder','Available'),
('Chaff Cutter 1','Cutter','Available'),
('Chaff Cutter 2','Cutter','Available');

INSERT INTO fertilizer (fertilizer_type, stock_level, unit) VALUES
('NPK 17-17-17',500,'kg'),
('DAP',450,'kg'),
('Urea',600,'kg'),
('CAN',400,'kg'),
('MOP',350,'kg'),
('NPK 20-10-10',550,'kg'),
('NPK 15-15-15',500,'kg'),
('Organic Compost',800,'kg'),
('Farmyard Manure',1000,'kg'),
('Ammonium Sulphate',300,'kg'),
('TSP',250,'kg'),
('Potassium Sulphate',275,'kg'),
('Calcium Nitrate',220,'kg'),
('Magnesium Sulphate',180,'kg'),
('Zinc Fertilizer',150,'kg'),
('Boron Fertilizer',120,'kg'),
('Phosphate Fertilizer',240,'kg'),
('Nitrogen Blend',400,'kg'),
('Organic Pellets',700,'kg'),
('Bio Fertilizer A',300,'kg'),
('Bio Fertilizer B',320,'kg'),
('Starter Fertilizer',280,'kg'),
('Vegetable Feed',350,'kg'),
('Root Booster',200,'kg'),
('Foliar Feed',180,'litre');

INSERT INTO harvest (crop_id, harvest_date, quantity) VALUES
(1,'2025-04-15',1200),(2,'2025-04-20',900),(3,'2025-06-10',1500),
(4,'2025-05-20',700),(5,'2025-05-30',850),(6,'2025-06-05',650),
(7,'2025-06-15',1000),(8,'2025-07-10',1100),(9,'2025-06-25',500),
(10,'2025-07-20',1300),(11,'2025-07-25',1250),(12,'2025-08-01',950),
(13,'2025-06-30',600),(14,'2025-08-15',900),(15,'2025-06-20',450),
(16,'2025-08-10',550),(17,'2025-11-01',1400),(18,'2025-10-15',1600),
(19,'2025-08-20',700),(20,'2025-08-25',650),(21,'2025-07-15',400),
(22,'2025-08-05',500),(23,'2025-09-01',750),(24,'2025-09-10',350),
(25,'2025-09-20',1000);

INSERT INTO customer (full_name, contact_details, address) VALUES
('Musanze Fresh Market','0789000001','Musanze'),
('Kigali Food Store','0789000002','Kigali'),
('Northern Grocers','0789000003','Musanze'),
('Green Basket Ltd','0789000004','Kigali'),
('Rwanda Fresh Foods','0789000005','Rubavu'),
('Horizon Supermarket','0789000006','Kigali'),
('Mountain View Hotel','0789000007','Musanze'),
('Volcano Restaurant','0789000008','Musanze'),
('Daily Choice Shop','0789000009','Ruhengeri'),
('Family Market','0789000010','Gicumbi'),
('Harvest House','0789000011','Kigali'),
('Healthy Plate Ltd','0789000012','Kigali'),
('East Africa Grocers','0789000013','Kigali'),
('Sunrise Hotel','0789000014','Musanze'),
('Community Food Centre','0789000015','Musanze'),
('Prime Foods','0789000016','Rubavu'),
('City Fresh Ltd','0789000017','Kigali'),
('Farmers Choice','0789000018','Musanze'),
('Golden Basket','0789000019','Kigali'),
('Good Harvest Ltd','0789000020','Byumba'),
('Fresh Corner','0789000021','Musanze'),
('Umucyo Restaurant','0789000022','Kigali'),
('Northern Hotel','0789000023','Musanze'),
('Market Link Ltd','0789000024','Kigali'),
('Village Foods','0789000025','Musanze');

INSERT INTO crop_worker (crop_id, worker_id, assigned_date, task_role)
SELECT i, ((i-1) % 25)+1, DATE '2025-01-05' + (i-1), 'Crop Care'
FROM generate_series(1,25) AS s(i);

INSERT INTO crop_worker (crop_id, worker_id, assigned_date, task_role)
SELECT i, (i % 25)+1, DATE '2025-02-01' + (i-1), 'Field Preparation'
FROM generate_series(1,25) AS s(i);

INSERT INTO equipment_assignment (equipment_id, worker_id, assigned_date, return_date)
SELECT i, ((i-1) % 25)+1, DATE '2025-03-01' + (i-1), DATE '2025-03-05' + (i-1)
FROM generate_series(1,20) AS s(i)
WHERE i NOT IN (5,19);

INSERT INTO equipment_maintenance (equipment_id, maintenance_date, description, status) VALUES
(5,'2025-03-10','Engine inspection','Completed'),
(19,'2025-04-12','Oil and filter replacement','Completed'),
(5,'2025-07-10','Transmission inspection','Scheduled'),
(19,'2025-08-05','Blade replacement','Scheduled'),
(3,'2025-05-20','Routine servicing','Completed'),
(7,'2025-06-01','Pump inspection','Completed'),
(11,'2025-06-10','Tiller servicing','Completed'),
(15,'2025-07-01','Seeder inspection','Completed'),
(20,'2025-07-15','Cart wheel replacement','Completed'),
(24,'2025-08-01','Cutter maintenance','Completed');

INSERT INTO fertilizer_usage (fertilizer_id, crop_id, quantity_used, usage_date)
SELECT ((i-1) % 25)+1, i, 10 + (i % 6) * 5, DATE '2025-02-01' + (i-1)
FROM generate_series(1,25) AS s(i);

INSERT INTO harvest_worker (harvest_id, worker_id, assigned_date, task_role)
SELECT i, ((i+4) % 25)+1, (SELECT harvest_date FROM harvest WHERE harvest_id=i), 'Harvesting'
FROM generate_series(1,25) AS s(i);

INSERT INTO sale (customer_id, sale_date, invoice_number, total_amount)
SELECT i, DATE '2025-04-20' + (i-1) * 7, 'INV-' || LPAD(i::text,4,'0'), 0
FROM generate_series(1,25) AS s(i);

-- Each sale initially uses a different harvest. Quantities are below harvested quantities.
INSERT INTO sale_item (sale_id, harvest_id, quantity_sold, unit_price)
SELECT i, i, CASE WHEN i <= 10 THEN 100 ELSE 80 END, 
       CASE WHEN i % 5 = 0 THEN 900 ELSE 700 END
FROM generate_series(1,25) AS s(i);

UPDATE sale s
SET total_amount = x.total
FROM (
    SELECT sale_id, SUM(quantity_sold * unit_price) AS total
    FROM sale_item
    GROUP BY sale_id
) x
WHERE s.sale_id = x.sale_id;


-- PHASE 6: DATABASE PROGRAMMING


-- ---------- 3 TRIGGERS ----------

-- Trigger 1: Do not allow fertilizer usage when stock is insufficient.
CREATE OR REPLACE FUNCTION check_fertilizer_stock()
RETURNS TRIGGER AS $$
DECLARE
    available NUMERIC(10,2);
BEGIN
    SELECT stock_level INTO available
    FROM fertilizer
    WHERE fertilizer_id = NEW.fertilizer_id
    FOR UPDATE;

    IF available < NEW.quantity_used THEN
        RAISE EXCEPTION 'Insufficient fertilizer stock.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_fertilizer_stock
BEFORE INSERT ON fertilizer_usage
FOR EACH ROW EXECUTE FUNCTION check_fertilizer_stock();

-- Trigger 2: Automatically reduce fertilizer stock after usage.
CREATE OR REPLACE FUNCTION reduce_fertilizer_stock()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE fertilizer
    SET stock_level = stock_level - NEW.quantity_used
    WHERE fertilizer_id = NEW.fertilizer_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_reduce_fertilizer_stock
AFTER INSERT ON fertilizer_usage
FOR EACH ROW EXECUTE FUNCTION reduce_fertilizer_stock();

-- Trigger 3: Prevent equipment under maintenance from being assigned.
CREATE OR REPLACE FUNCTION prevent_maintenance_equipment_assignment()
RETURNS TRIGGER AS $$
DECLARE
    current_status VARCHAR(20);
BEGIN
    SELECT status INTO current_status
    FROM equipment
    WHERE equipment_id = NEW.equipment_id;

    IF current_status = 'Under Maintenance' THEN
        RAISE EXCEPTION 'Equipment is under maintenance and cannot be assigned.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_prevent_maintenance_assignment
BEFORE INSERT ON equipment_assignment
FOR EACH ROW EXECUTE FUNCTION prevent_maintenance_equipment_assignment();

-- Trigger 4: Prevent selling more than the available harvested quantity.
CREATE OR REPLACE FUNCTION check_sale_quantity()
RETURNS TRIGGER AS $$
DECLARE
    remaining NUMERIC(12,2);
BEGIN
    SELECT h.quantity - COALESCE(SUM(si.quantity_sold),0)
    INTO remaining
    FROM harvest h
    LEFT JOIN sale_item si ON si.harvest_id = h.harvest_id
    WHERE h.harvest_id = NEW.harvest_id
    GROUP BY h.quantity;

    IF NEW.quantity_sold > COALESCE(remaining,0) THEN
        RAISE EXCEPTION 'Quantity sold cannot exceed available harvested quantity.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_sale_quantity
BEFORE INSERT ON sale_item
FOR EACH ROW EXECUTE FUNCTION check_sale_quantity();

-- ---------- 2 USER-DEFINED FUNCTIONS ----------

CREATE OR REPLACE FUNCTION get_customer_total_sales(p_customer_id INTEGER)
RETURNS NUMERIC(12,2) AS $$
DECLARE
    total_sales NUMERIC(12,2);
BEGIN
    SELECT COALESCE(SUM(total_amount),0)
    INTO total_sales
    FROM sale
    WHERE customer_id = p_customer_id;

    RETURN total_sales;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_remaining_harvest(p_harvest_id INTEGER)
RETURNS NUMERIC(12,2) AS $$
DECLARE
    harvested NUMERIC(12,2);
    sold NUMERIC(12,2);
BEGIN
    SELECT quantity INTO harvested
    FROM harvest
    WHERE harvest_id = p_harvest_id;

    SELECT COALESCE(SUM(quantity_sold),0)
    INTO sold
    FROM sale_item
    WHERE harvest_id = p_harvest_id;

    RETURN harvested - sold;
END;
$$ LANGUAGE plpgsql;

-- ---------- 3 STORED PROCEDURES ----------

CREATE OR REPLACE PROCEDURE record_harvest(
    p_crop_id INTEGER,
    p_harvest_date DATE,
    p_quantity NUMERIC(10,2)
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'Harvest quantity must be greater than zero.';
    END IF;

    INSERT INTO harvest(crop_id, harvest_date, quantity)
    VALUES(p_crop_id, p_harvest_date, p_quantity);
END;
$$;

CREATE OR REPLACE PROCEDURE use_fertilizer(
    p_fertilizer_id INTEGER,
    p_crop_id INTEGER,
    p_quantity NUMERIC(10,2),
    p_usage_date DATE
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'Fertilizer quantity must be greater than zero.';
    END IF;

    INSERT INTO fertilizer_usage(fertilizer_id, crop_id, quantity_used, usage_date)
    VALUES(p_fertilizer_id, p_crop_id, p_quantity, p_usage_date);
END;
$$;

CREATE OR REPLACE PROCEDURE record_sale(
    p_customer_id INTEGER,
    p_harvest_id INTEGER,
    p_quantity NUMERIC(10,2),
    p_unit_price NUMERIC(12,2),
    p_sale_date DATE
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_sale_id INTEGER;
    v_remaining NUMERIC(12,2);
    v_invoice VARCHAR(30);
BEGIN
    IF p_quantity <= 0 OR p_unit_price < 0 THEN
        RAISE EXCEPTION 'Invalid sale quantity or unit price.';
    END IF;

    v_remaining := get_remaining_harvest(p_harvest_id);

    IF p_quantity > v_remaining THEN
        RAISE EXCEPTION 'Sale quantity exceeds available harvested quantity.';
    END IF;

    INSERT INTO sale(customer_id, sale_date, invoice_number, total_amount)
    VALUES(
        p_customer_id,
        p_sale_date,
        'AUTO-' || TO_CHAR(CURRENT_TIMESTAMP,'YYYYMMDDHH24MISSMS'),
        p_quantity * p_unit_price
    )
    RETURNING sale_id, invoice_number INTO v_sale_id, v_invoice;

    INSERT INTO sale_item(sale_id, harvest_id, quantity_sold, unit_price)
    VALUES(v_sale_id, p_harvest_id, p_quantity, p_unit_price);
END;
$$;

-- ---------- 5 VIEWS ----------

CREATE OR REPLACE VIEW crop_production_view AS
SELECT
    c.crop_id,
    c.crop_type,
    c.plot_number,
    c.status,
    COALESCE(SUM(h.quantity),0) AS total_harvested
FROM crop c
LEFT JOIN harvest h ON h.crop_id = c.crop_id
GROUP BY c.crop_id, c.crop_type, c.plot_number, c.status;

CREATE OR REPLACE VIEW worker_crop_view AS
SELECT
    w.worker_id,
    w.employee_id,
    w.fname || ' ' || w.lname AS worker_name,
    c.crop_id,
    c.crop_type,
    cw.assigned_date,
    cw.task_role
FROM worker w
JOIN crop_worker cw ON cw.worker_id = w.worker_id
JOIN crop c ON c.crop_id = cw.crop_id;

CREATE OR REPLACE VIEW fertilizer_stock_view AS
SELECT
    fertilizer_id,
    fertilizer_type,
    stock_level,
    unit,
    CASE
        WHEN stock_level < 100 THEN 'LOW'
        ELSE 'OK'
    END AS stock_status
FROM fertilizer;

CREATE OR REPLACE VIEW harvest_summary_view AS
SELECT
    h.harvest_id,
    c.crop_type,
    h.harvest_date,
    h.quantity AS harvested_quantity,
    COALESCE(SUM(si.quantity_sold),0) AS sold_quantity,
    h.quantity - COALESCE(SUM(si.quantity_sold),0) AS remaining_quantity
FROM harvest h
JOIN crop c ON c.crop_id = h.crop_id
LEFT JOIN sale_item si ON si.harvest_id = h.harvest_id
GROUP BY h.harvest_id, c.crop_type, h.harvest_date, h.quantity;

CREATE OR REPLACE VIEW sales_summary_view AS
SELECT
    s.sale_id,
    s.invoice_number,
    s.sale_date,
    c.full_name AS customer,
    s.total_amount
FROM sale s
JOIN customer c ON c.customer_id = s.customer_id;

-- ---------- 10 ADVANCED SQL QUERIES ----------

-- Query 1: Total production by crop
SELECT c.crop_type, SUM(h.quantity) AS total_harvested
FROM crop c
JOIN harvest h ON h.crop_id = c.crop_id
GROUP BY c.crop_type
ORDER BY total_harvested DESC;

-- Query 2: Crops producing above the average harvest
SELECT c.crop_type, SUM(h.quantity) AS total_harvested
FROM crop c
JOIN harvest h ON h.crop_id = c.crop_id
GROUP BY c.crop_id, c.crop_type
HAVING SUM(h.quantity) > (
    SELECT AVG(total_quantity)
    FROM (
        SELECT SUM(quantity) AS total_quantity
        FROM harvest
        GROUP BY crop_id
    ) x
)
ORDER BY total_harvested DESC;

-- Query 3: Customer sales ranking using a window function
SELECT
    c.full_name,
    SUM(s.total_amount) AS total_spent,
    RANK() OVER (ORDER BY SUM(s.total_amount) DESC) AS sales_rank
FROM customer c
JOIN sale s ON s.customer_id = c.customer_id
GROUP BY c.customer_id, c.full_name
ORDER BY sales_rank;

-- Query 4: Monthly sales totals
SELECT
    DATE_TRUNC('month', sale_date)::date AS sales_month,
    SUM(total_amount) AS monthly_sales
FROM sale
GROUP BY DATE_TRUNC('month', sale_date)
ORDER BY sales_month;

-- Query 5: Workers assigned to more than one crop
SELECT
    w.employee_id,
    w.fname || ' ' || w.lname AS worker_name,
    COUNT(DISTINCT cw.crop_id) AS crop_count
FROM worker w
JOIN crop_worker cw ON cw.worker_id = w.worker_id
GROUP BY w.worker_id, w.employee_id, w.fname, w.lname
HAVING COUNT(DISTINCT cw.crop_id) > 1
ORDER BY crop_count DESC;

-- Query 6: Low fertilizer stock
SELECT fertilizer_type, stock_level, unit
FROM fertilizer
WHERE stock_level < 100
ORDER BY stock_level;

-- Query 7: Equipment currently unavailable
SELECT equipment_name, equipment_type, status
FROM equipment
WHERE status <> 'Available'
ORDER BY equipment_name;

-- Query 8: Harvest remaining after sales
SELECT *
FROM harvest_summary_view
WHERE remaining_quantity > 0
ORDER BY remaining_quantity DESC;

-- Query 9: Highest-value sales
SELECT
    s.invoice_number,
    c.full_name,
    s.total_amount,
    s.sale_date
FROM sale s
JOIN customer c ON c.customer_id = s.customer_id
WHERE s.total_amount > (
    SELECT AVG(total_amount) FROM sale
)
ORDER BY s.total_amount DESC;

-- Query 10: Crop production with worker count
SELECT
    c.crop_type,
    COALESCE(SUM(h.quantity),0) AS total_harvested,
    COUNT(DISTINCT cw.worker_id) AS workers_assigned
FROM crop c
LEFT JOIN harvest h ON h.crop_id = c.crop_id
LEFT JOIN crop_worker cw ON cw.crop_id = c.crop_id
GROUP BY c.crop_id, c.crop_type
ORDER BY total_harvested DESC;


-- PHASE 7: SECURITY

CREATE ROLE farm_admin NOLOGIN;
CREATE ROLE farm_manager NOLOGIN;
CREATE ROLE inventory_officer NOLOGIN;
CREATE ROLE sales_officer NOLOGIN;
CREATE ROLE farm_worker NOLOGIN;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO farm_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO farm_admin;

GRANT SELECT, INSERT, UPDATE, DELETE ON
    farm, crop, worker, harvest, crop_worker, harvest_worker, equipment_assignment
TO farm_manager;

GRANT SELECT, INSERT, UPDATE ON equipment, fertilizer, fertilizer_usage,
    equipment_maintenance TO inventory_officer;

GRANT SELECT, INSERT, UPDATE ON customer, sale, sale_item TO sales_officer;

GRANT SELECT ON crop, crop_worker, harvest, harvest_worker, equipment TO farm_worker;

GRANT SELECT ON
    crop_production_view, worker_crop_view, fertilizer_stock_view,
    harvest_summary_view, sales_summary_view
TO farm_manager, inventory_officer, sales_officer, farm_worker;

